import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  const handleClick = (e, path) => {
   e.preventDefault()

    if (path === "/api/hello") {
      // console.log("I clicked on the About Page");
      // then you can: 
      // router.push(path)
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Circulo Taringuero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Circulo <a href="https://taringa.net">Taringuero</a> 
        </h1>

        <p className={styles.description}>
          Ingrese el usuario en el campo
        </p>

        <div id="cuerpo">
          <div className={styles.description}>
            <input className={styles.code} type="text" placeholder="Ingresar Usuario"/>
          </div>
          <br/>
          <div className={styles.description}>
            <button className={styles.btn} onClick={(e) => handleClick(e, "/api/hello")}>Generar</button>
          </div>
        </div>

        <div className={styles.card}>Al ingresar el usuario se generar una imagen con todos los usuarios que te rodean</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
